# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-03 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20, verbose_name='课程名称')),
                ('first_module', models.CharField(max_length=30, verbose_name='一级模块')),
                ('second_module', models.CharField(max_length=30, verbose_name='二级模块')),
                ('knowledge_point', models.CharField(blank=True, max_length=100, null=True, verbose_name='知识点')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'knowledgebase',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='题目名称')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('difficulty_level', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], max_length=6, verbose_name='难易程度')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('knowledge_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgequestions.KnowledgeBase', verbose_name='知识模块')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'db_table': 'questionbank',
            },
        ),
    ]
