# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-03 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgequestions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='knowledge_module',
        ),
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
        migrations.DeleteModel(
            name='QuestionBank',
        ),
    ]
