# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgequestions', '0002_auto_20180110_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='module',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='knowledgebase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='knowledgequestions.KnowledgeBase', verbose_name='二级模块'),
        ),
    ]
