# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-29 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='英文名')),
                ('password', models.CharField(max_length=200, verbose_name='，密码')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别')),
                ('degree', models.CharField(choices=[('1', '小学'), ('2', '初中'), ('3', '中专/高中'), ('4', '专科/本科'), ('5', '硕士研究生'), ('6', '博士研究生')], max_length=1, verbose_name='学历')),
                ('reg_date', models.DateTimeField(verbose_name='注册时间')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('height', models.IntegerField(verbose_name='身高')),
                ('weight', models.IntegerField(verbose_name='体重')),
                ('learning', models.TextField(verbose_name='学习经历')),
                ('allergies', models.TextField(verbose_name='过敏史')),
                ('status', models.CharField(choices=[('1', '学习期内'), ('2', '毕业')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='英文名')),
                ('password', models.CharField(max_length=200, verbose_name='，密码')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别')),
                ('degree', models.CharField(choices=[('1', '小学'), ('2', '初中'), ('3', '中专/高中'), ('4', '专科/本科'), ('5', '硕士研究生'), ('6', '博士研究生')], max_length=1, verbose_name='学历')),
                ('reg_date', models.DateTimeField(verbose_name='注册时间')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('school', models.CharField(max_length=50, verbose_name='学校')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
