# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-29 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.RenameField(
            model_name='students',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='status',
        ),
        migrations.AlterField(
            model_name='students',
            name='degree',
            field=models.CharField(choices=[('', '中专/高中'), ('bk', '专科/本科'), ('ss', '硕士研究生'), ('bs', '博士研究生')], max_length=1, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=200, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='students',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间'),
        ),
    ]
