# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-10 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180110_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class', verbose_name='所属班级'),
        ),
    ]
