# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-03 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class'),
        ('homework', '0002_auto_20180103_1533'),
        ('teachers', '0005_auto_20180103_1533'),
        ('students', '0002_auto_20180103_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassModel',
        ),
    ]
