# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-29 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='题目名')),
                ('content', models.TextField(verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('class_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ClassModel', verbose_name='班级')),
            ],
            options={
                'verbose_name_plural': '作业管理',
                'verbose_name': '作业管理',
            },
        ),
    ]
