# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-10 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import homework.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledgequestions', '0001_initial'),
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bonus', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='加分题')),
                ('refer_complete_time', models.CharField(default='10', max_length=5, verbose_name='参考完成时间(分钟数)')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class', verbose_name='班级')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgequestions.QuestionBank', verbose_name='题目')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher', verbose_name='教师')),
            ],
            options={
                'verbose_name': '作业布置',
                'verbose_name_plural': '作业布置',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to=homework.models.stu_directory_path, verbose_name='上传文件路径')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '文件上传',
                'verbose_name_plural': '文件上传',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='题目状态')),
                ('complete_time', models.CharField(default='0', max_length=5, verbose_name='完成时间(分钟数)')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Assignment', verbose_name='题目')),
                ('file_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.File', verbose_name='上传文件路径')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
            },
        ),
    ]
