# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-29 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='username',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='degree',
            field=models.CharField(choices=[('undergraduate', '专科/本科'), ('master', '硕士研究生'), ('doctor', '博士研究生')], max_length=1, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=1, verbose_name='性别'),
        ),
    ]
