# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='passwd',
            field=models.CharField(max_length=200, verbose_name='密码'),
        ),
    ]
