# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-30 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20171229_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersmodel',
            old_name='class_name',
            new_name='class_teacher',
        ),
    ]
